import {
  filterExpedientes,
  formatFechaActa,
  type ExpedienteFilters,
  type ExpedienteRow,
} from '@/lib/expediente/table'

export type { ExpedienteFilters, ExpedienteRow }
export { filterExpedientes, formatFechaActa }

/** Datos de demostración para pruebas o storybook. El listado en app usa datos reales. */
export const EXPEDIENTES_MOCK: ExpedienteRow[] = [
  {
    id: '1',
    profesionalNombre: 'Carlos Alexander Balmaceda',
    profesionalIniciales: 'CB',
    fechaActa: '2026-04-24T15:00:00.000Z',
    nomenclatura: '18-88/418288',
    titular: 'SERVICIO PROVINCIAL DE SALUD (Poseedor)',
    ubicacion: 'Calle Mercedes Gallardo Valdez s/nº esquina Av. 9 de Julio, Resistencia',
  },
  {
    id: '2',
    profesionalNombre: 'Carlos Alexander Balmaceda',
    profesionalIniciales: 'CB',
    fechaActa: '2026-04-24T15:00:00.000Z',
    nomenclatura: '18-88/418288',
    titular: 'SERVICIO PROVINCIAL DE SALUD (Poseedor)',
    ubicacion: 'Calle Mercedes Gallardo Valdez s/nº esquina Av. 9 de Julio, Resistencia',
  },
  {
    id: '3',
    profesionalNombre: 'María Elena Férnandez',
    profesionalIniciales: 'MF',
    fechaActa: '2026-03-10T14:30:00.000Z',
    nomenclatura: '12-45/301122',
    titular: 'MUNICIPALIDAD DE RESISTENCIA',
    ubicacion: 'B° VILLA DON ANTONIO M.Btá. 2da. Sección Mz. 7 Casa 21',
  },
  {
    id: '4',
    profesionalNombre: 'Juan Pérez',
    profesionalIniciales: 'JP',
    fechaActa: '2026-02-02T11:00:00.000Z',
    nomenclatura: '09-11/200045',
    titular: 'COOPERATIVA EL PROGRESO LTDA.',
    ubicacion: 'Ruta Provincial Nº 6 km 12, Margen Izquierdo',
  },
  {
    id: '5',
    profesionalNombre: 'Ana Gómez',
    profesionalIniciales: 'AG',
    fechaActa: '2026-05-01T09:15:00.000Z',
    nomenclatura: '22-01/510003',
    titular: 'GARCÍA LUIS ALBERTO',
    ubicacion: 'Av. Sarmiento 1450, 1º piso, Resistencia',
  },
  {
    id: '6',
    profesionalNombre: 'Carlos Alexander Balmaceda',
    profesionalIniciales: 'CB',
    fechaActa: '2026-01-18T16:45:00.000Z',
    nomenclatura: '07-33/189901',
    titular: 'ESTADO PROVINCIAL — IPVD',
    ubicacion: 'Predio fiscal parcela 4, Colonia Popular',
  },
  {
    id: '7',
    profesionalNombre: 'María Elena Férnandez',
    profesionalIniciales: 'MF',
    fechaActa: '2025-12-05T10:00:00.000Z',
    nomenclatura: '15-02/445566',
    titular: 'ASOCIACIÓN CIVIL LOS ALAMOS',
    ubicacion: 'Camino rural 14 bis entre desvíos A y B',
  },
  {
    id: '8',
    profesionalNombre: 'Juan Pérez',
    profesionalIniciales: 'JP',
    fechaActa: '2026-04-02T13:20:00.000Z',
    nomenclatura: '03-99/120088',
    titular: 'BANCO DE LA NACIÓN ARGENTINA',
    ubicacion: 'Microcentro — Edificio histórico — Sótano archivo',
  },
  {
    id: '9',
    profesionalNombre: 'Ana Gómez',
    profesionalIniciales: 'AG',
    fechaActa: '2026-06-12T08:00:00.000Z',
    nomenclatura: '11-11/600111',
    titular: 'FIDEICOMISO URBANO NORTE',
    ubicacion: 'Loteo Los Pinos, manzana 3 lote 8',
  },
  {
    id: '10',
    profesionalNombre: 'Carlos Alexander Balmaceda',
    profesionalIniciales: 'CB',
    fechaActa: '2025-11-20T12:30:00.000Z',
    nomenclatura: '04-04/990044',
    titular: 'IGLESIA EVANGÉLICA DEL RÍO',
    ubicacion: 'Bv. Roca 2200, esquina Italia',
  },
]
